# docker-compose.yml

version: "3.8"

services:
  api:
    build: .
    container_name: sql-api-container
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sql-net
    command:
      ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]

  db:
    image: postgres:14
    container_name: postgres-db
    env_file:
      - .env
    # We are back to using a named volume, which is managed by Docker.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - sql-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sql-net:
    driver: bridge

# Define the named volume for data persistence
volumes:
  postgres_data:
